# Generated by Django 2.2.4 on 2024-05-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20240526_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default=' ', max_length=45),
        ),
    ]
