# Generated by Django 2.2.4 on 2024-05-26 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20240526_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 9, 18, 53, 972368)),
        ),
        migrations.AddField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 9, 18, 53, 972390)),
        ),
    ]
